################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryCells.c \
../Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryContinuous.c \
../Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryInfoAux.c \
../Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryPeriodic.c \
../Modules/dsdl_generated/src/ardupilot.equipment.proximity_sensor.Proximity.c \
../Modules/dsdl_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.c \
../Modules/dsdl_generated/src/ardupilot.gnss.Heading.c \
../Modules/dsdl_generated/src/ardupilot.gnss.MovingBaselineData.c \
../Modules/dsdl_generated/src/ardupilot.gnss.RelPosHeading.c \
../Modules/dsdl_generated/src/ardupilot.gnss.Status.c \
../Modules/dsdl_generated/src/ardupilot.indication.Button.c \
../Modules/dsdl_generated/src/ardupilot.indication.NotifyState.c \
../Modules/dsdl_generated/src/ardupilot.indication.SafetyState.c \
../Modules/dsdl_generated/src/com.aeronavics.ExtenderCtrl.c \
../Modules/dsdl_generated/src/com.aeronavics.ExtenderInfo.c \
../Modules/dsdl_generated/src/com.aeronavics.FanStatus.c \
../Modules/dsdl_generated/src/com.aeronavics.OBSTACLE.c \
../Modules/dsdl_generated/src/com.aeronavics.ProximitySensor.c \
../Modules/dsdl_generated/src/com.aeronavics.RegulatorStatus.c \
../Modules/dsdl_generated/src/com.aeronavics.SprayCtrl.c \
../Modules/dsdl_generated/src/com.aeronavics.SprayInfo.c \
../Modules/dsdl_generated/src/com.hex.equipment.flow.Measurement.c \
../Modules/dsdl_generated/src/com.himark.servo.ServoCmd.c \
../Modules/dsdl_generated/src/com.himark.servo.ServoInfo.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.GetEscID.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.RawCommand.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetID_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetID_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_req.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_res.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg1.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg2.c \
../Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg3.c \
../Modules/dsdl_generated/src/com.tmotor.esc.FocCtrl.c \
../Modules/dsdl_generated/src/com.tmotor.esc.PUSHCAN.c \
../Modules/dsdl_generated/src/com.tmotor.esc.PUSHSCI.c \
../Modules/dsdl_generated/src/com.tmotor.esc.ParamCfg.c \
../Modules/dsdl_generated/src/com.tmotor.esc.ParamGet.c \
../Modules/dsdl_generated/src/com.volz.servo.ActuatorStatus.c \
../Modules/dsdl_generated/src/com.xacti.CopterAttStatus.c \
../Modules/dsdl_generated/src/com.xacti.GimbalAttitudeStatus.c \
../Modules/dsdl_generated/src/com.xacti.GimbalControlData.c \
../Modules/dsdl_generated/src/com.xacti.GnssStatus.c \
../Modules/dsdl_generated/src/com.xacti.GnssStatusReq.c \
../Modules/dsdl_generated/src/uavcan.CoarseOrientation.c \
../Modules/dsdl_generated/src/uavcan.Timestamp.c \
../Modules/dsdl_generated/src/uavcan.equipment.actuator.ArrayCommand.c \
../Modules/dsdl_generated/src/uavcan.equipment.actuator.Command.c \
../Modules/dsdl_generated/src/uavcan.equipment.actuator.Status.c \
../Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.c \
../Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.c \
../Modules/dsdl_generated/src/uavcan.equipment.ahrs.RawIMU.c \
../Modules/dsdl_generated/src/uavcan.equipment.ahrs.Solution.c \
../Modules/dsdl_generated/src/uavcan.equipment.air_data.AngleOfAttack.c \
../Modules/dsdl_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.c \
../Modules/dsdl_generated/src/uavcan.equipment.air_data.RawAirData.c \
../Modules/dsdl_generated/src/uavcan.equipment.air_data.Sideslip.c \
../Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticPressure.c \
../Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticTemperature.c \
../Modules/dsdl_generated/src/uavcan.equipment.air_data.TrueAirspeed.c \
../Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.c \
../Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.c \
../Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Mode.c \
../Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Status.c \
../Modules/dsdl_generated/src/uavcan.equipment.device.Temperature.c \
../Modules/dsdl_generated/src/uavcan.equipment.esc.RPMCommand.c \
../Modules/dsdl_generated/src/uavcan.equipment.esc.RawCommand.c \
../Modules/dsdl_generated/src/uavcan.equipment.esc.Status.c \
../Modules/dsdl_generated/src/uavcan.equipment.esc.StatusExtended.c \
../Modules/dsdl_generated/src/uavcan.equipment.gnss.Auxiliary.c \
../Modules/dsdl_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.c \
../Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix.c \
../Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix2.c \
../Modules/dsdl_generated/src/uavcan.equipment.gnss.RTCMStream.c \
../Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Command.c \
../Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Status.c \
../Modules/dsdl_generated/src/uavcan.equipment.ice.FuelTankStatus.c \
../Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.c \
../Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.Status.c \
../Modules/dsdl_generated/src/uavcan.equipment.indication.BeepCommand.c \
../Modules/dsdl_generated/src/uavcan.equipment.indication.LightsCommand.c \
../Modules/dsdl_generated/src/uavcan.equipment.indication.RGB565.c \
../Modules/dsdl_generated/src/uavcan.equipment.indication.SingleLightCommand.c \
../Modules/dsdl_generated/src/uavcan.equipment.power.BatteryInfo.c \
../Modules/dsdl_generated/src/uavcan.equipment.power.CircuitStatus.c \
../Modules/dsdl_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.c \
../Modules/dsdl_generated/src/uavcan.equipment.range_sensor.Measurement.c \
../Modules/dsdl_generated/src/uavcan.equipment.safety.ArmingStatus.c \
../Modules/dsdl_generated/src/uavcan.navigation.GlobalNavigationSolution.c \
../Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.CANIfaceStats.c \
../Modules/dsdl_generated/src/uavcan.protocol.DataTypeKind.c \
../Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.GlobalTimeSync.c \
../Modules/dsdl_generated/src/uavcan.protocol.HardwareVersion.c \
../Modules/dsdl_generated/src/uavcan.protocol.NodeStatus.c \
../Modules/dsdl_generated/src/uavcan.protocol.Panic.c \
../Modules/dsdl_generated/src/uavcan.protocol.RestartNode_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.RestartNode_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.SoftwareVersion.c \
../Modules/dsdl_generated/src/uavcan.protocol.debug.KeyValue.c \
../Modules/dsdl_generated/src/uavcan.protocol.debug.LogLevel.c \
../Modules/dsdl_generated/src/uavcan.protocol.debug.LogMessage.c \
../Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.Allocation.c \
../Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.c \
../Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.c \
../Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.enumeration.Indication.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.Delete_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.Delete_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.EntryType.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.Error.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.Path.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.Read_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.Read_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.Write_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.file.Write_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.param.Empty.c \
../Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_req.c \
../Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_res.c \
../Modules/dsdl_generated/src/uavcan.protocol.param.NumericValue.c \
../Modules/dsdl_generated/src/uavcan.protocol.param.Value.c \
../Modules/dsdl_generated/src/uavcan.tunnel.Broadcast.c \
../Modules/dsdl_generated/src/uavcan.tunnel.Call_req.c \
../Modules/dsdl_generated/src/uavcan.tunnel.Call_res.c \
../Modules/dsdl_generated/src/uavcan.tunnel.Protocol.c \
../Modules/dsdl_generated/src/uavcan.tunnel.SerialConfig.c \
../Modules/dsdl_generated/src/uavcan.tunnel.Targetted.c 

C_DEPS += \
./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryCells.d \
./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryContinuous.d \
./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryInfoAux.d \
./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryPeriodic.d \
./Modules/dsdl_generated/src/ardupilot.equipment.proximity_sensor.Proximity.d \
./Modules/dsdl_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.d \
./Modules/dsdl_generated/src/ardupilot.gnss.Heading.d \
./Modules/dsdl_generated/src/ardupilot.gnss.MovingBaselineData.d \
./Modules/dsdl_generated/src/ardupilot.gnss.RelPosHeading.d \
./Modules/dsdl_generated/src/ardupilot.gnss.Status.d \
./Modules/dsdl_generated/src/ardupilot.indication.Button.d \
./Modules/dsdl_generated/src/ardupilot.indication.NotifyState.d \
./Modules/dsdl_generated/src/ardupilot.indication.SafetyState.d \
./Modules/dsdl_generated/src/com.aeronavics.ExtenderCtrl.d \
./Modules/dsdl_generated/src/com.aeronavics.ExtenderInfo.d \
./Modules/dsdl_generated/src/com.aeronavics.FanStatus.d \
./Modules/dsdl_generated/src/com.aeronavics.OBSTACLE.d \
./Modules/dsdl_generated/src/com.aeronavics.ProximitySensor.d \
./Modules/dsdl_generated/src/com.aeronavics.RegulatorStatus.d \
./Modules/dsdl_generated/src/com.aeronavics.SprayCtrl.d \
./Modules/dsdl_generated/src/com.aeronavics.SprayInfo.d \
./Modules/dsdl_generated/src/com.hex.equipment.flow.Measurement.d \
./Modules/dsdl_generated/src/com.himark.servo.ServoCmd.d \
./Modules/dsdl_generated/src/com.himark.servo.ServoInfo.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetEscID.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.RawCommand.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_req.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_res.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg1.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg2.d \
./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg3.d \
./Modules/dsdl_generated/src/com.tmotor.esc.FocCtrl.d \
./Modules/dsdl_generated/src/com.tmotor.esc.PUSHCAN.d \
./Modules/dsdl_generated/src/com.tmotor.esc.PUSHSCI.d \
./Modules/dsdl_generated/src/com.tmotor.esc.ParamCfg.d \
./Modules/dsdl_generated/src/com.tmotor.esc.ParamGet.d \
./Modules/dsdl_generated/src/com.volz.servo.ActuatorStatus.d \
./Modules/dsdl_generated/src/com.xacti.CopterAttStatus.d \
./Modules/dsdl_generated/src/com.xacti.GimbalAttitudeStatus.d \
./Modules/dsdl_generated/src/com.xacti.GimbalControlData.d \
./Modules/dsdl_generated/src/com.xacti.GnssStatus.d \
./Modules/dsdl_generated/src/com.xacti.GnssStatusReq.d \
./Modules/dsdl_generated/src/uavcan.CoarseOrientation.d \
./Modules/dsdl_generated/src/uavcan.Timestamp.d \
./Modules/dsdl_generated/src/uavcan.equipment.actuator.ArrayCommand.d \
./Modules/dsdl_generated/src/uavcan.equipment.actuator.Command.d \
./Modules/dsdl_generated/src/uavcan.equipment.actuator.Status.d \
./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.d \
./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d \
./Modules/dsdl_generated/src/uavcan.equipment.ahrs.RawIMU.d \
./Modules/dsdl_generated/src/uavcan.equipment.ahrs.Solution.d \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.AngleOfAttack.d \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.d \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.RawAirData.d \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.Sideslip.d \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticPressure.d \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticTemperature.d \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.TrueAirspeed.d \
./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.d \
./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.d \
./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Mode.d \
./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Status.d \
./Modules/dsdl_generated/src/uavcan.equipment.device.Temperature.d \
./Modules/dsdl_generated/src/uavcan.equipment.esc.RPMCommand.d \
./Modules/dsdl_generated/src/uavcan.equipment.esc.RawCommand.d \
./Modules/dsdl_generated/src/uavcan.equipment.esc.Status.d \
./Modules/dsdl_generated/src/uavcan.equipment.esc.StatusExtended.d \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.Auxiliary.d \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.d \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix.d \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix2.d \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.RTCMStream.d \
./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Command.d \
./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Status.d \
./Modules/dsdl_generated/src/uavcan.equipment.ice.FuelTankStatus.d \
./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d \
./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.Status.d \
./Modules/dsdl_generated/src/uavcan.equipment.indication.BeepCommand.d \
./Modules/dsdl_generated/src/uavcan.equipment.indication.LightsCommand.d \
./Modules/dsdl_generated/src/uavcan.equipment.indication.RGB565.d \
./Modules/dsdl_generated/src/uavcan.equipment.indication.SingleLightCommand.d \
./Modules/dsdl_generated/src/uavcan.equipment.power.BatteryInfo.d \
./Modules/dsdl_generated/src/uavcan.equipment.power.CircuitStatus.d \
./Modules/dsdl_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d \
./Modules/dsdl_generated/src/uavcan.equipment.range_sensor.Measurement.d \
./Modules/dsdl_generated/src/uavcan.equipment.safety.ArmingStatus.d \
./Modules/dsdl_generated/src/uavcan.navigation.GlobalNavigationSolution.d \
./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.CANIfaceStats.d \
./Modules/dsdl_generated/src/uavcan.protocol.DataTypeKind.d \
./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.GlobalTimeSync.d \
./Modules/dsdl_generated/src/uavcan.protocol.HardwareVersion.d \
./Modules/dsdl_generated/src/uavcan.protocol.NodeStatus.d \
./Modules/dsdl_generated/src/uavcan.protocol.Panic.d \
./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.SoftwareVersion.d \
./Modules/dsdl_generated/src/uavcan.protocol.debug.KeyValue.d \
./Modules/dsdl_generated/src/uavcan.protocol.debug.LogLevel.d \
./Modules/dsdl_generated/src/uavcan.protocol.debug.LogMessage.d \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.Allocation.d \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.d \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.d \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Indication.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.EntryType.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.Error.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.Path.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.Read_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.Read_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.Write_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.file.Write_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.param.Empty.d \
./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_req.d \
./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_res.d \
./Modules/dsdl_generated/src/uavcan.protocol.param.NumericValue.d \
./Modules/dsdl_generated/src/uavcan.protocol.param.Value.d \
./Modules/dsdl_generated/src/uavcan.tunnel.Broadcast.d \
./Modules/dsdl_generated/src/uavcan.tunnel.Call_req.d \
./Modules/dsdl_generated/src/uavcan.tunnel.Call_res.d \
./Modules/dsdl_generated/src/uavcan.tunnel.Protocol.d \
./Modules/dsdl_generated/src/uavcan.tunnel.SerialConfig.d \
./Modules/dsdl_generated/src/uavcan.tunnel.Targetted.d 

OBJS += \
./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryCells.o \
./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryContinuous.o \
./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryInfoAux.o \
./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryPeriodic.o \
./Modules/dsdl_generated/src/ardupilot.equipment.proximity_sensor.Proximity.o \
./Modules/dsdl_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.o \
./Modules/dsdl_generated/src/ardupilot.gnss.Heading.o \
./Modules/dsdl_generated/src/ardupilot.gnss.MovingBaselineData.o \
./Modules/dsdl_generated/src/ardupilot.gnss.RelPosHeading.o \
./Modules/dsdl_generated/src/ardupilot.gnss.Status.o \
./Modules/dsdl_generated/src/ardupilot.indication.Button.o \
./Modules/dsdl_generated/src/ardupilot.indication.NotifyState.o \
./Modules/dsdl_generated/src/ardupilot.indication.SafetyState.o \
./Modules/dsdl_generated/src/com.aeronavics.ExtenderCtrl.o \
./Modules/dsdl_generated/src/com.aeronavics.ExtenderInfo.o \
./Modules/dsdl_generated/src/com.aeronavics.FanStatus.o \
./Modules/dsdl_generated/src/com.aeronavics.OBSTACLE.o \
./Modules/dsdl_generated/src/com.aeronavics.ProximitySensor.o \
./Modules/dsdl_generated/src/com.aeronavics.RegulatorStatus.o \
./Modules/dsdl_generated/src/com.aeronavics.SprayCtrl.o \
./Modules/dsdl_generated/src/com.aeronavics.SprayInfo.o \
./Modules/dsdl_generated/src/com.hex.equipment.flow.Measurement.o \
./Modules/dsdl_generated/src/com.himark.servo.ServoCmd.o \
./Modules/dsdl_generated/src/com.himark.servo.ServoInfo.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetEscID.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.RawCommand.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_req.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_res.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg1.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg2.o \
./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg3.o \
./Modules/dsdl_generated/src/com.tmotor.esc.FocCtrl.o \
./Modules/dsdl_generated/src/com.tmotor.esc.PUSHCAN.o \
./Modules/dsdl_generated/src/com.tmotor.esc.PUSHSCI.o \
./Modules/dsdl_generated/src/com.tmotor.esc.ParamCfg.o \
./Modules/dsdl_generated/src/com.tmotor.esc.ParamGet.o \
./Modules/dsdl_generated/src/com.volz.servo.ActuatorStatus.o \
./Modules/dsdl_generated/src/com.xacti.CopterAttStatus.o \
./Modules/dsdl_generated/src/com.xacti.GimbalAttitudeStatus.o \
./Modules/dsdl_generated/src/com.xacti.GimbalControlData.o \
./Modules/dsdl_generated/src/com.xacti.GnssStatus.o \
./Modules/dsdl_generated/src/com.xacti.GnssStatusReq.o \
./Modules/dsdl_generated/src/uavcan.CoarseOrientation.o \
./Modules/dsdl_generated/src/uavcan.Timestamp.o \
./Modules/dsdl_generated/src/uavcan.equipment.actuator.ArrayCommand.o \
./Modules/dsdl_generated/src/uavcan.equipment.actuator.Command.o \
./Modules/dsdl_generated/src/uavcan.equipment.actuator.Status.o \
./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.o \
./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o \
./Modules/dsdl_generated/src/uavcan.equipment.ahrs.RawIMU.o \
./Modules/dsdl_generated/src/uavcan.equipment.ahrs.Solution.o \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.AngleOfAttack.o \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.o \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.RawAirData.o \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.Sideslip.o \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticPressure.o \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticTemperature.o \
./Modules/dsdl_generated/src/uavcan.equipment.air_data.TrueAirspeed.o \
./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.o \
./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.o \
./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Mode.o \
./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Status.o \
./Modules/dsdl_generated/src/uavcan.equipment.device.Temperature.o \
./Modules/dsdl_generated/src/uavcan.equipment.esc.RPMCommand.o \
./Modules/dsdl_generated/src/uavcan.equipment.esc.RawCommand.o \
./Modules/dsdl_generated/src/uavcan.equipment.esc.Status.o \
./Modules/dsdl_generated/src/uavcan.equipment.esc.StatusExtended.o \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.Auxiliary.o \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.o \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix.o \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix2.o \
./Modules/dsdl_generated/src/uavcan.equipment.gnss.RTCMStream.o \
./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Command.o \
./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Status.o \
./Modules/dsdl_generated/src/uavcan.equipment.ice.FuelTankStatus.o \
./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o \
./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.Status.o \
./Modules/dsdl_generated/src/uavcan.equipment.indication.BeepCommand.o \
./Modules/dsdl_generated/src/uavcan.equipment.indication.LightsCommand.o \
./Modules/dsdl_generated/src/uavcan.equipment.indication.RGB565.o \
./Modules/dsdl_generated/src/uavcan.equipment.indication.SingleLightCommand.o \
./Modules/dsdl_generated/src/uavcan.equipment.power.BatteryInfo.o \
./Modules/dsdl_generated/src/uavcan.equipment.power.CircuitStatus.o \
./Modules/dsdl_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o \
./Modules/dsdl_generated/src/uavcan.equipment.range_sensor.Measurement.o \
./Modules/dsdl_generated/src/uavcan.equipment.safety.ArmingStatus.o \
./Modules/dsdl_generated/src/uavcan.navigation.GlobalNavigationSolution.o \
./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.CANIfaceStats.o \
./Modules/dsdl_generated/src/uavcan.protocol.DataTypeKind.o \
./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.GlobalTimeSync.o \
./Modules/dsdl_generated/src/uavcan.protocol.HardwareVersion.o \
./Modules/dsdl_generated/src/uavcan.protocol.NodeStatus.o \
./Modules/dsdl_generated/src/uavcan.protocol.Panic.o \
./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.SoftwareVersion.o \
./Modules/dsdl_generated/src/uavcan.protocol.debug.KeyValue.o \
./Modules/dsdl_generated/src/uavcan.protocol.debug.LogLevel.o \
./Modules/dsdl_generated/src/uavcan.protocol.debug.LogMessage.o \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.Allocation.o \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.o \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.o \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Indication.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.EntryType.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.Error.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.Path.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.Read_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.Read_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.Write_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.file.Write_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.param.Empty.o \
./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_req.o \
./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_res.o \
./Modules/dsdl_generated/src/uavcan.protocol.param.NumericValue.o \
./Modules/dsdl_generated/src/uavcan.protocol.param.Value.o \
./Modules/dsdl_generated/src/uavcan.tunnel.Broadcast.o \
./Modules/dsdl_generated/src/uavcan.tunnel.Call_req.o \
./Modules/dsdl_generated/src/uavcan.tunnel.Call_res.o \
./Modules/dsdl_generated/src/uavcan.tunnel.Protocol.o \
./Modules/dsdl_generated/src/uavcan.tunnel.SerialConfig.o \
./Modules/dsdl_generated/src/uavcan.tunnel.Targetted.o 


# Each subdirectory must supply rules for building sources it contributes
Modules/dsdl_generated/src/%.o Modules/dsdl_generated/src/%.su Modules/dsdl_generated/src/%.cyclo: ../Modules/dsdl_generated/src/%.c Modules/dsdl_generated/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G474xx -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Modules-2f-dsdl_generated-2f-src

clean-Modules-2f-dsdl_generated-2f-src:
	-$(RM) ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryCells.cyclo ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryCells.d ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryCells.o ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryCells.su ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryContinuous.cyclo ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryContinuous.d ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryContinuous.o ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryContinuous.su ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryInfoAux.cyclo ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryInfoAux.d ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryInfoAux.o ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryInfoAux.su ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryPeriodic.cyclo ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryPeriodic.d ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryPeriodic.o ./Modules/dsdl_generated/src/ardupilot.equipment.power.BatteryPeriodic.su ./Modules/dsdl_generated/src/ardupilot.equipment.proximity_sensor.Proximity.cyclo ./Modules/dsdl_generated/src/ardupilot.equipment.proximity_sensor.Proximity.d ./Modules/dsdl_generated/src/ardupilot.equipment.proximity_sensor.Proximity.o ./Modules/dsdl_generated/src/ardupilot.equipment.proximity_sensor.Proximity.su ./Modules/dsdl_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.cyclo ./Modules/dsdl_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.d ./Modules/dsdl_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.o ./Modules/dsdl_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.su ./Modules/dsdl_generated/src/ardupilot.gnss.Heading.cyclo ./Modules/dsdl_generated/src/ardupilot.gnss.Heading.d ./Modules/dsdl_generated/src/ardupilot.gnss.Heading.o ./Modules/dsdl_generated/src/ardupilot.gnss.Heading.su ./Modules/dsdl_generated/src/ardupilot.gnss.MovingBaselineData.cyclo ./Modules/dsdl_generated/src/ardupilot.gnss.MovingBaselineData.d ./Modules/dsdl_generated/src/ardupilot.gnss.MovingBaselineData.o ./Modules/dsdl_generated/src/ardupilot.gnss.MovingBaselineData.su ./Modules/dsdl_generated/src/ardupilot.gnss.RelPosHeading.cyclo ./Modules/dsdl_generated/src/ardupilot.gnss.RelPosHeading.d ./Modules/dsdl_generated/src/ardupilot.gnss.RelPosHeading.o ./Modules/dsdl_generated/src/ardupilot.gnss.RelPosHeading.su ./Modules/dsdl_generated/src/ardupilot.gnss.Status.cyclo ./Modules/dsdl_generated/src/ardupilot.gnss.Status.d ./Modules/dsdl_generated/src/ardupilot.gnss.Status.o ./Modules/dsdl_generated/src/ardupilot.gnss.Status.su ./Modules/dsdl_generated/src/ardupilot.indication.Button.cyclo ./Modules/dsdl_generated/src/ardupilot.indication.Button.d ./Modules/dsdl_generated/src/ardupilot.indication.Button.o ./Modules/dsdl_generated/src/ardupilot.indication.Button.su ./Modules/dsdl_generated/src/ardupilot.indication.NotifyState.cyclo ./Modules/dsdl_generated/src/ardupilot.indication.NotifyState.d ./Modules/dsdl_generated/src/ardupilot.indication.NotifyState.o ./Modules/dsdl_generated/src/ardupilot.indication.NotifyState.su ./Modules/dsdl_generated/src/ardupilot.indication.SafetyState.cyclo ./Modules/dsdl_generated/src/ardupilot.indication.SafetyState.d ./Modules/dsdl_generated/src/ardupilot.indication.SafetyState.o ./Modules/dsdl_generated/src/ardupilot.indication.SafetyState.su ./Modules/dsdl_generated/src/com.aeronavics.ExtenderCtrl.cyclo ./Modules/dsdl_generated/src/com.aeronavics.ExtenderCtrl.d ./Modules/dsdl_generated/src/com.aeronavics.ExtenderCtrl.o ./Modules/dsdl_generated/src/com.aeronavics.ExtenderCtrl.su ./Modules/dsdl_generated/src/com.aeronavics.ExtenderInfo.cyclo ./Modules/dsdl_generated/src/com.aeronavics.ExtenderInfo.d ./Modules/dsdl_generated/src/com.aeronavics.ExtenderInfo.o ./Modules/dsdl_generated/src/com.aeronavics.ExtenderInfo.su ./Modules/dsdl_generated/src/com.aeronavics.FanStatus.cyclo ./Modules/dsdl_generated/src/com.aeronavics.FanStatus.d ./Modules/dsdl_generated/src/com.aeronavics.FanStatus.o ./Modules/dsdl_generated/src/com.aeronavics.FanStatus.su ./Modules/dsdl_generated/src/com.aeronavics.OBSTACLE.cyclo ./Modules/dsdl_generated/src/com.aeronavics.OBSTACLE.d ./Modules/dsdl_generated/src/com.aeronavics.OBSTACLE.o ./Modules/dsdl_generated/src/com.aeronavics.OBSTACLE.su ./Modules/dsdl_generated/src/com.aeronavics.ProximitySensor.cyclo ./Modules/dsdl_generated/src/com.aeronavics.ProximitySensor.d ./Modules/dsdl_generated/src/com.aeronavics.ProximitySensor.o ./Modules/dsdl_generated/src/com.aeronavics.ProximitySensor.su ./Modules/dsdl_generated/src/com.aeronavics.RegulatorStatus.cyclo ./Modules/dsdl_generated/src/com.aeronavics.RegulatorStatus.d ./Modules/dsdl_generated/src/com.aeronavics.RegulatorStatus.o ./Modules/dsdl_generated/src/com.aeronavics.RegulatorStatus.su ./Modules/dsdl_generated/src/com.aeronavics.SprayCtrl.cyclo ./Modules/dsdl_generated/src/com.aeronavics.SprayCtrl.d ./Modules/dsdl_generated/src/com.aeronavics.SprayCtrl.o ./Modules/dsdl_generated/src/com.aeronavics.SprayCtrl.su ./Modules/dsdl_generated/src/com.aeronavics.SprayInfo.cyclo ./Modules/dsdl_generated/src/com.aeronavics.SprayInfo.d ./Modules/dsdl_generated/src/com.aeronavics.SprayInfo.o ./Modules/dsdl_generated/src/com.aeronavics.SprayInfo.su ./Modules/dsdl_generated/src/com.hex.equipment.flow.Measurement.cyclo ./Modules/dsdl_generated/src/com.hex.equipment.flow.Measurement.d ./Modules/dsdl_generated/src/com.hex.equipment.flow.Measurement.o ./Modules/dsdl_generated/src/com.hex.equipment.flow.Measurement.su ./Modules/dsdl_generated/src/com.himark.servo.ServoCmd.cyclo ./Modules/dsdl_generated/src/com.himark.servo.ServoCmd.d ./Modules/dsdl_generated/src/com.himark.servo.ServoCmd.o ./Modules/dsdl_generated/src/com.himark.servo.ServoCmd.su
	-$(RM) ./Modules/dsdl_generated/src/com.himark.servo.ServoInfo.cyclo ./Modules/dsdl_generated/src/com.himark.servo.ServoInfo.d ./Modules/dsdl_generated/src/com.himark.servo.ServoInfo.o ./Modules/dsdl_generated/src/com.himark.servo.ServoInfo.su ./Modules/dsdl_generated/src/com.hobbywing.esc.GetEscID.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.GetEscID.d ./Modules/dsdl_generated/src/com.hobbywing.esc.GetEscID.o ./Modules/dsdl_generated/src/com.hobbywing.esc.GetEscID.su ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.GetMajorConfig_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.RawCommand.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.RawCommand.d ./Modules/dsdl_generated/src/com.hobbywing.esc.RawCommand.o ./Modules/dsdl_generated/src/com.hobbywing.esc.RawCommand.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SelfTest_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetAngle_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetBaud_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetDirection_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetID_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetLED_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_res.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetReportingFrequency_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_req.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_req.d ./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_req.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_req.su ./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_res.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_res.d
	-$(RM) ./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_res.o ./Modules/dsdl_generated/src/com.hobbywing.esc.SetThrottleSource_res.su ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg1.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg1.d ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg1.o ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg1.su ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg2.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg2.d ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg2.o ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg2.su ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg3.cyclo ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg3.d ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg3.o ./Modules/dsdl_generated/src/com.hobbywing.esc.StatusMsg3.su ./Modules/dsdl_generated/src/com.tmotor.esc.FocCtrl.cyclo ./Modules/dsdl_generated/src/com.tmotor.esc.FocCtrl.d ./Modules/dsdl_generated/src/com.tmotor.esc.FocCtrl.o ./Modules/dsdl_generated/src/com.tmotor.esc.FocCtrl.su ./Modules/dsdl_generated/src/com.tmotor.esc.PUSHCAN.cyclo ./Modules/dsdl_generated/src/com.tmotor.esc.PUSHCAN.d ./Modules/dsdl_generated/src/com.tmotor.esc.PUSHCAN.o ./Modules/dsdl_generated/src/com.tmotor.esc.PUSHCAN.su ./Modules/dsdl_generated/src/com.tmotor.esc.PUSHSCI.cyclo ./Modules/dsdl_generated/src/com.tmotor.esc.PUSHSCI.d ./Modules/dsdl_generated/src/com.tmotor.esc.PUSHSCI.o ./Modules/dsdl_generated/src/com.tmotor.esc.PUSHSCI.su ./Modules/dsdl_generated/src/com.tmotor.esc.ParamCfg.cyclo ./Modules/dsdl_generated/src/com.tmotor.esc.ParamCfg.d ./Modules/dsdl_generated/src/com.tmotor.esc.ParamCfg.o ./Modules/dsdl_generated/src/com.tmotor.esc.ParamCfg.su ./Modules/dsdl_generated/src/com.tmotor.esc.ParamGet.cyclo ./Modules/dsdl_generated/src/com.tmotor.esc.ParamGet.d ./Modules/dsdl_generated/src/com.tmotor.esc.ParamGet.o ./Modules/dsdl_generated/src/com.tmotor.esc.ParamGet.su ./Modules/dsdl_generated/src/com.volz.servo.ActuatorStatus.cyclo ./Modules/dsdl_generated/src/com.volz.servo.ActuatorStatus.d ./Modules/dsdl_generated/src/com.volz.servo.ActuatorStatus.o ./Modules/dsdl_generated/src/com.volz.servo.ActuatorStatus.su ./Modules/dsdl_generated/src/com.xacti.CopterAttStatus.cyclo ./Modules/dsdl_generated/src/com.xacti.CopterAttStatus.d ./Modules/dsdl_generated/src/com.xacti.CopterAttStatus.o ./Modules/dsdl_generated/src/com.xacti.CopterAttStatus.su ./Modules/dsdl_generated/src/com.xacti.GimbalAttitudeStatus.cyclo ./Modules/dsdl_generated/src/com.xacti.GimbalAttitudeStatus.d ./Modules/dsdl_generated/src/com.xacti.GimbalAttitudeStatus.o ./Modules/dsdl_generated/src/com.xacti.GimbalAttitudeStatus.su ./Modules/dsdl_generated/src/com.xacti.GimbalControlData.cyclo ./Modules/dsdl_generated/src/com.xacti.GimbalControlData.d ./Modules/dsdl_generated/src/com.xacti.GimbalControlData.o ./Modules/dsdl_generated/src/com.xacti.GimbalControlData.su ./Modules/dsdl_generated/src/com.xacti.GnssStatus.cyclo ./Modules/dsdl_generated/src/com.xacti.GnssStatus.d ./Modules/dsdl_generated/src/com.xacti.GnssStatus.o ./Modules/dsdl_generated/src/com.xacti.GnssStatus.su ./Modules/dsdl_generated/src/com.xacti.GnssStatusReq.cyclo ./Modules/dsdl_generated/src/com.xacti.GnssStatusReq.d ./Modules/dsdl_generated/src/com.xacti.GnssStatusReq.o ./Modules/dsdl_generated/src/com.xacti.GnssStatusReq.su ./Modules/dsdl_generated/src/uavcan.CoarseOrientation.cyclo ./Modules/dsdl_generated/src/uavcan.CoarseOrientation.d ./Modules/dsdl_generated/src/uavcan.CoarseOrientation.o ./Modules/dsdl_generated/src/uavcan.CoarseOrientation.su ./Modules/dsdl_generated/src/uavcan.Timestamp.cyclo ./Modules/dsdl_generated/src/uavcan.Timestamp.d ./Modules/dsdl_generated/src/uavcan.Timestamp.o ./Modules/dsdl_generated/src/uavcan.Timestamp.su ./Modules/dsdl_generated/src/uavcan.equipment.actuator.ArrayCommand.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.actuator.ArrayCommand.d ./Modules/dsdl_generated/src/uavcan.equipment.actuator.ArrayCommand.o ./Modules/dsdl_generated/src/uavcan.equipment.actuator.ArrayCommand.su ./Modules/dsdl_generated/src/uavcan.equipment.actuator.Command.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.actuator.Command.d ./Modules/dsdl_generated/src/uavcan.equipment.actuator.Command.o ./Modules/dsdl_generated/src/uavcan.equipment.actuator.Command.su ./Modules/dsdl_generated/src/uavcan.equipment.actuator.Status.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.actuator.Status.d ./Modules/dsdl_generated/src/uavcan.equipment.actuator.Status.o ./Modules/dsdl_generated/src/uavcan.equipment.actuator.Status.su ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.d ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.o ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.su ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.su ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.RawIMU.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.RawIMU.d ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.RawIMU.o ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.RawIMU.su ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.Solution.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.Solution.d ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.Solution.o ./Modules/dsdl_generated/src/uavcan.equipment.ahrs.Solution.su ./Modules/dsdl_generated/src/uavcan.equipment.air_data.AngleOfAttack.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.air_data.AngleOfAttack.d ./Modules/dsdl_generated/src/uavcan.equipment.air_data.AngleOfAttack.o
	-$(RM) ./Modules/dsdl_generated/src/uavcan.equipment.air_data.AngleOfAttack.su ./Modules/dsdl_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.d ./Modules/dsdl_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.o ./Modules/dsdl_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.su ./Modules/dsdl_generated/src/uavcan.equipment.air_data.RawAirData.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.air_data.RawAirData.d ./Modules/dsdl_generated/src/uavcan.equipment.air_data.RawAirData.o ./Modules/dsdl_generated/src/uavcan.equipment.air_data.RawAirData.su ./Modules/dsdl_generated/src/uavcan.equipment.air_data.Sideslip.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.air_data.Sideslip.d ./Modules/dsdl_generated/src/uavcan.equipment.air_data.Sideslip.o ./Modules/dsdl_generated/src/uavcan.equipment.air_data.Sideslip.su ./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticPressure.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticPressure.d ./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticPressure.o ./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticPressure.su ./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticTemperature.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticTemperature.d ./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticTemperature.o ./Modules/dsdl_generated/src/uavcan.equipment.air_data.StaticTemperature.su ./Modules/dsdl_generated/src/uavcan.equipment.air_data.TrueAirspeed.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.air_data.TrueAirspeed.d ./Modules/dsdl_generated/src/uavcan.equipment.air_data.TrueAirspeed.o ./Modules/dsdl_generated/src/uavcan.equipment.air_data.TrueAirspeed.su ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.d ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.o ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.AngularCommand.su ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.d ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.o ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.GEOPOICommand.su ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Mode.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Mode.d ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Mode.o ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Mode.su ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Status.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Status.d ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Status.o ./Modules/dsdl_generated/src/uavcan.equipment.camera_gimbal.Status.su ./Modules/dsdl_generated/src/uavcan.equipment.device.Temperature.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.device.Temperature.d ./Modules/dsdl_generated/src/uavcan.equipment.device.Temperature.o ./Modules/dsdl_generated/src/uavcan.equipment.device.Temperature.su ./Modules/dsdl_generated/src/uavcan.equipment.esc.RPMCommand.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.esc.RPMCommand.d ./Modules/dsdl_generated/src/uavcan.equipment.esc.RPMCommand.o ./Modules/dsdl_generated/src/uavcan.equipment.esc.RPMCommand.su ./Modules/dsdl_generated/src/uavcan.equipment.esc.RawCommand.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.esc.RawCommand.d ./Modules/dsdl_generated/src/uavcan.equipment.esc.RawCommand.o ./Modules/dsdl_generated/src/uavcan.equipment.esc.RawCommand.su ./Modules/dsdl_generated/src/uavcan.equipment.esc.Status.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.esc.Status.d ./Modules/dsdl_generated/src/uavcan.equipment.esc.Status.o ./Modules/dsdl_generated/src/uavcan.equipment.esc.Status.su ./Modules/dsdl_generated/src/uavcan.equipment.esc.StatusExtended.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.esc.StatusExtended.d ./Modules/dsdl_generated/src/uavcan.equipment.esc.StatusExtended.o ./Modules/dsdl_generated/src/uavcan.equipment.esc.StatusExtended.su ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Auxiliary.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Auxiliary.d ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Auxiliary.o ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Auxiliary.su ./Modules/dsdl_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.d ./Modules/dsdl_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.o ./Modules/dsdl_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.su ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix.d ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix.o ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix.su ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix2.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix2.d ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix2.o ./Modules/dsdl_generated/src/uavcan.equipment.gnss.Fix2.su ./Modules/dsdl_generated/src/uavcan.equipment.gnss.RTCMStream.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.gnss.RTCMStream.d ./Modules/dsdl_generated/src/uavcan.equipment.gnss.RTCMStream.o ./Modules/dsdl_generated/src/uavcan.equipment.gnss.RTCMStream.su ./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Command.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Command.d ./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Command.o ./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Command.su ./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Status.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Status.d
	-$(RM) ./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Status.o ./Modules/dsdl_generated/src/uavcan.equipment.hardpoint.Status.su ./Modules/dsdl_generated/src/uavcan.equipment.ice.FuelTankStatus.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.ice.FuelTankStatus.d ./Modules/dsdl_generated/src/uavcan.equipment.ice.FuelTankStatus.o ./Modules/dsdl_generated/src/uavcan.equipment.ice.FuelTankStatus.su ./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d ./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o ./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.su ./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.Status.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.Status.d ./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.Status.o ./Modules/dsdl_generated/src/uavcan.equipment.ice.reciprocating.Status.su ./Modules/dsdl_generated/src/uavcan.equipment.indication.BeepCommand.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.indication.BeepCommand.d ./Modules/dsdl_generated/src/uavcan.equipment.indication.BeepCommand.o ./Modules/dsdl_generated/src/uavcan.equipment.indication.BeepCommand.su ./Modules/dsdl_generated/src/uavcan.equipment.indication.LightsCommand.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.indication.LightsCommand.d ./Modules/dsdl_generated/src/uavcan.equipment.indication.LightsCommand.o ./Modules/dsdl_generated/src/uavcan.equipment.indication.LightsCommand.su ./Modules/dsdl_generated/src/uavcan.equipment.indication.RGB565.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.indication.RGB565.d ./Modules/dsdl_generated/src/uavcan.equipment.indication.RGB565.o ./Modules/dsdl_generated/src/uavcan.equipment.indication.RGB565.su ./Modules/dsdl_generated/src/uavcan.equipment.indication.SingleLightCommand.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.indication.SingleLightCommand.d ./Modules/dsdl_generated/src/uavcan.equipment.indication.SingleLightCommand.o ./Modules/dsdl_generated/src/uavcan.equipment.indication.SingleLightCommand.su ./Modules/dsdl_generated/src/uavcan.equipment.power.BatteryInfo.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.power.BatteryInfo.d ./Modules/dsdl_generated/src/uavcan.equipment.power.BatteryInfo.o ./Modules/dsdl_generated/src/uavcan.equipment.power.BatteryInfo.su ./Modules/dsdl_generated/src/uavcan.equipment.power.CircuitStatus.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.power.CircuitStatus.d ./Modules/dsdl_generated/src/uavcan.equipment.power.CircuitStatus.o ./Modules/dsdl_generated/src/uavcan.equipment.power.CircuitStatus.su ./Modules/dsdl_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d ./Modules/dsdl_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o ./Modules/dsdl_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.su ./Modules/dsdl_generated/src/uavcan.equipment.range_sensor.Measurement.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.range_sensor.Measurement.d ./Modules/dsdl_generated/src/uavcan.equipment.range_sensor.Measurement.o ./Modules/dsdl_generated/src/uavcan.equipment.range_sensor.Measurement.su ./Modules/dsdl_generated/src/uavcan.equipment.safety.ArmingStatus.cyclo ./Modules/dsdl_generated/src/uavcan.equipment.safety.ArmingStatus.d ./Modules/dsdl_generated/src/uavcan.equipment.safety.ArmingStatus.o ./Modules/dsdl_generated/src/uavcan.equipment.safety.ArmingStatus.su ./Modules/dsdl_generated/src/uavcan.navigation.GlobalNavigationSolution.cyclo ./Modules/dsdl_generated/src/uavcan.navigation.GlobalNavigationSolution.d ./Modules/dsdl_generated/src/uavcan.navigation.GlobalNavigationSolution.o ./Modules/dsdl_generated/src/uavcan.navigation.GlobalNavigationSolution.su ./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_req.d ./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_req.o ./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_req.su ./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_res.d ./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_res.o ./Modules/dsdl_generated/src/uavcan.protocol.AccessCommandShell_res.su ./Modules/dsdl_generated/src/uavcan.protocol.CANIfaceStats.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.CANIfaceStats.d ./Modules/dsdl_generated/src/uavcan.protocol.CANIfaceStats.o ./Modules/dsdl_generated/src/uavcan.protocol.CANIfaceStats.su ./Modules/dsdl_generated/src/uavcan.protocol.DataTypeKind.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.DataTypeKind.d ./Modules/dsdl_generated/src/uavcan.protocol.DataTypeKind.o ./Modules/dsdl_generated/src/uavcan.protocol.DataTypeKind.su ./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_req.d ./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_req.o ./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_req.su ./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_res.d ./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_res.o ./Modules/dsdl_generated/src/uavcan.protocol.GetDataTypeInfo_res.su ./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_req.d ./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_req.o ./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_req.su ./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_res.d
	-$(RM) ./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_res.o ./Modules/dsdl_generated/src/uavcan.protocol.GetNodeInfo_res.su ./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_req.d ./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_req.o ./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_req.su ./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_res.d ./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_res.o ./Modules/dsdl_generated/src/uavcan.protocol.GetTransportStats_res.su ./Modules/dsdl_generated/src/uavcan.protocol.GlobalTimeSync.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.GlobalTimeSync.d ./Modules/dsdl_generated/src/uavcan.protocol.GlobalTimeSync.o ./Modules/dsdl_generated/src/uavcan.protocol.GlobalTimeSync.su ./Modules/dsdl_generated/src/uavcan.protocol.HardwareVersion.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.HardwareVersion.d ./Modules/dsdl_generated/src/uavcan.protocol.HardwareVersion.o ./Modules/dsdl_generated/src/uavcan.protocol.HardwareVersion.su ./Modules/dsdl_generated/src/uavcan.protocol.NodeStatus.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.NodeStatus.d ./Modules/dsdl_generated/src/uavcan.protocol.NodeStatus.o ./Modules/dsdl_generated/src/uavcan.protocol.NodeStatus.su ./Modules/dsdl_generated/src/uavcan.protocol.Panic.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.Panic.d ./Modules/dsdl_generated/src/uavcan.protocol.Panic.o ./Modules/dsdl_generated/src/uavcan.protocol.Panic.su ./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_req.d ./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_req.o ./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_req.su ./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_res.d ./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_res.o ./Modules/dsdl_generated/src/uavcan.protocol.RestartNode_res.su ./Modules/dsdl_generated/src/uavcan.protocol.SoftwareVersion.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.SoftwareVersion.d ./Modules/dsdl_generated/src/uavcan.protocol.SoftwareVersion.o ./Modules/dsdl_generated/src/uavcan.protocol.SoftwareVersion.su ./Modules/dsdl_generated/src/uavcan.protocol.debug.KeyValue.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.debug.KeyValue.d ./Modules/dsdl_generated/src/uavcan.protocol.debug.KeyValue.o ./Modules/dsdl_generated/src/uavcan.protocol.debug.KeyValue.su ./Modules/dsdl_generated/src/uavcan.protocol.debug.LogLevel.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.debug.LogLevel.d ./Modules/dsdl_generated/src/uavcan.protocol.debug.LogLevel.o ./Modules/dsdl_generated/src/uavcan.protocol.debug.LogLevel.su ./Modules/dsdl_generated/src/uavcan.protocol.debug.LogMessage.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.debug.LogMessage.d ./Modules/dsdl_generated/src/uavcan.protocol.debug.LogMessage.o ./Modules/dsdl_generated/src/uavcan.protocol.debug.LogMessage.su ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.Allocation.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.Allocation.d ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.Allocation.o ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.Allocation.su ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.su ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.su ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.d ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.o ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.su ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.d ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.o ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.su ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.su ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o ./Modules/dsdl_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.su ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_req.d ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_req.o ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_req.su ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_res.d
	-$(RM) ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_res.o ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Begin_res.su ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Indication.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Indication.d ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Indication.o ./Modules/dsdl_generated/src/uavcan.protocol.enumeration.Indication.su ./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d ./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o ./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.su ./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d ./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o ./Modules/dsdl_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.su ./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_req.d ./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_req.o ./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_req.su ./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_res.d ./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_res.o ./Modules/dsdl_generated/src/uavcan.protocol.file.Delete_res.su ./Modules/dsdl_generated/src/uavcan.protocol.file.EntryType.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.EntryType.d ./Modules/dsdl_generated/src/uavcan.protocol.file.EntryType.o ./Modules/dsdl_generated/src/uavcan.protocol.file.EntryType.su ./Modules/dsdl_generated/src/uavcan.protocol.file.Error.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.Error.d ./Modules/dsdl_generated/src/uavcan.protocol.file.Error.o ./Modules/dsdl_generated/src/uavcan.protocol.file.Error.su ./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d ./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o ./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.su ./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d ./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o ./Modules/dsdl_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.su ./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_req.d ./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_req.o ./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_req.su ./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_res.d ./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_res.o ./Modules/dsdl_generated/src/uavcan.protocol.file.GetInfo_res.su ./Modules/dsdl_generated/src/uavcan.protocol.file.Path.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.Path.d ./Modules/dsdl_generated/src/uavcan.protocol.file.Path.o ./Modules/dsdl_generated/src/uavcan.protocol.file.Path.su ./Modules/dsdl_generated/src/uavcan.protocol.file.Read_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.Read_req.d ./Modules/dsdl_generated/src/uavcan.protocol.file.Read_req.o ./Modules/dsdl_generated/src/uavcan.protocol.file.Read_req.su ./Modules/dsdl_generated/src/uavcan.protocol.file.Read_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.Read_res.d ./Modules/dsdl_generated/src/uavcan.protocol.file.Read_res.o ./Modules/dsdl_generated/src/uavcan.protocol.file.Read_res.su ./Modules/dsdl_generated/src/uavcan.protocol.file.Write_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.Write_req.d ./Modules/dsdl_generated/src/uavcan.protocol.file.Write_req.o ./Modules/dsdl_generated/src/uavcan.protocol.file.Write_req.su ./Modules/dsdl_generated/src/uavcan.protocol.file.Write_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.file.Write_res.d ./Modules/dsdl_generated/src/uavcan.protocol.file.Write_res.o ./Modules/dsdl_generated/src/uavcan.protocol.file.Write_res.su ./Modules/dsdl_generated/src/uavcan.protocol.param.Empty.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.param.Empty.d ./Modules/dsdl_generated/src/uavcan.protocol.param.Empty.o ./Modules/dsdl_generated/src/uavcan.protocol.param.Empty.su ./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_req.d ./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_req.o ./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_req.su ./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_res.d ./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_res.o ./Modules/dsdl_generated/src/uavcan.protocol.param.ExecuteOpcode_res.su ./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_req.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_req.d ./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_req.o ./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_req.su ./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_res.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_res.d ./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_res.o ./Modules/dsdl_generated/src/uavcan.protocol.param.GetSet_res.su ./Modules/dsdl_generated/src/uavcan.protocol.param.NumericValue.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.param.NumericValue.d ./Modules/dsdl_generated/src/uavcan.protocol.param.NumericValue.o
	-$(RM) ./Modules/dsdl_generated/src/uavcan.protocol.param.NumericValue.su ./Modules/dsdl_generated/src/uavcan.protocol.param.Value.cyclo ./Modules/dsdl_generated/src/uavcan.protocol.param.Value.d ./Modules/dsdl_generated/src/uavcan.protocol.param.Value.o ./Modules/dsdl_generated/src/uavcan.protocol.param.Value.su ./Modules/dsdl_generated/src/uavcan.tunnel.Broadcast.cyclo ./Modules/dsdl_generated/src/uavcan.tunnel.Broadcast.d ./Modules/dsdl_generated/src/uavcan.tunnel.Broadcast.o ./Modules/dsdl_generated/src/uavcan.tunnel.Broadcast.su ./Modules/dsdl_generated/src/uavcan.tunnel.Call_req.cyclo ./Modules/dsdl_generated/src/uavcan.tunnel.Call_req.d ./Modules/dsdl_generated/src/uavcan.tunnel.Call_req.o ./Modules/dsdl_generated/src/uavcan.tunnel.Call_req.su ./Modules/dsdl_generated/src/uavcan.tunnel.Call_res.cyclo ./Modules/dsdl_generated/src/uavcan.tunnel.Call_res.d ./Modules/dsdl_generated/src/uavcan.tunnel.Call_res.o ./Modules/dsdl_generated/src/uavcan.tunnel.Call_res.su ./Modules/dsdl_generated/src/uavcan.tunnel.Protocol.cyclo ./Modules/dsdl_generated/src/uavcan.tunnel.Protocol.d ./Modules/dsdl_generated/src/uavcan.tunnel.Protocol.o ./Modules/dsdl_generated/src/uavcan.tunnel.Protocol.su ./Modules/dsdl_generated/src/uavcan.tunnel.SerialConfig.cyclo ./Modules/dsdl_generated/src/uavcan.tunnel.SerialConfig.d ./Modules/dsdl_generated/src/uavcan.tunnel.SerialConfig.o ./Modules/dsdl_generated/src/uavcan.tunnel.SerialConfig.su ./Modules/dsdl_generated/src/uavcan.tunnel.Targetted.cyclo ./Modules/dsdl_generated/src/uavcan.tunnel.Targetted.d ./Modules/dsdl_generated/src/uavcan.tunnel.Targetted.o ./Modules/dsdl_generated/src/uavcan.tunnel.Targetted.su

.PHONY: clean-Modules-2f-dsdl_generated-2f-src

